(* open struct *)
(*   module Bwd = struct *)
(*     module Proto = Protos.Grpc_reflection_v1_reflection.Grpc.Reflection.V1 *)
(*     module Service = Proto.ServerReflection *)
(*   end *)
(**)
(*   let server_reflection_info = *)
(*     let module Op = Ocaml_protoc_plugin in *)
(*     let module Rpc = Bwd.Service.ServerReflectionInfo in *)
(*     Utils.Grpc.create_unary_handler *)
(*       (module Rpc) *)
(*       ~h:(fun ~decode ~encode buf -> *)
(*         let open Let.Result in *)
(*         Logs.debug (fun m -> m "Received ServerReflectionInfo request: %s" buf); *)
(*         let* request = Op.Reader.create buf |> decode in *)
(*         let reply = Rpc.Response.make ~original_request:request () in *)
(*         return @@ (encode reply |> Op.Writer.contents)) *)
(*   ;; *)
(**)
(*   let service = Grpc_eio.Server.Service.(v () |> server_reflection_info |> handle_request) *)
(* end *)
(**)
(* let register = *)
(*   Grpc_eio.Server.add_service *)
(*     ~name: *)
(*       [%string *)
(*         {|$(Option.value ~default:"" *)
(*       (Bwd.Service.ServerReflectionInfo.package_name)).$(Bwd.Service.ServerReflectionInfo.service_name)|}] *)
(*     ~service *)
(* ;; *)
