-- Create enum type "article_state"
CREATE TYPE "public"."article_state" AS ENUM ('published_public', 'published_private', 'draft');
-- Create enum type "comment_target_type"
CREATE TYPE "public"."comment_target_type" AS ENUM ('articles', 'memos');
-- Create enum type "memo_state"
CREATE TYPE "public"."memo_state" AS ENUM ('public', 'private');
-- Create "users" table
CREATE TABLE "public"."users" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(255) NOT NULL, "email" character varying(255) NOT NULL, "display_name" character varying(255) NOT NULL, "bio" text NOT NULL, "avatar_url" character varying(255) NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"));
-- Create index "users_email_key" to table: "users"
CREATE UNIQUE INDEX "users_email_key" ON "public"."users" ("email");
-- Create "articles" table
CREATE TABLE "public"."articles" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "title" character varying(255) NOT NULL, "content" text NOT NULL, "state" "public"."article_state" NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "articles_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "tags" table
CREATE TABLE "public"."tags" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "name" character varying(255) NOT NULL, "user_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "tags_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create index "tags_user_id_name_key" to table: "tags"
CREATE UNIQUE INDEX "tags_user_id_name_key" ON "public"."tags" ("user_id", "name");
-- Create "articles_tags" table
CREATE TABLE "public"."articles_tags" ("article_id" bigint NOT NULL, "tag_id" bigint NOT NULL, PRIMARY KEY ("article_id", "tag_id"), CONSTRAINT "articles_tags_article_id_fkey" FOREIGN KEY ("article_id") REFERENCES "public"."articles" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "articles_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "comments" table
CREATE TABLE "public"."comments" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "target_id" bigint NOT NULL, "target_type" "public"."comment_target_type" NOT NULL, "user_id" bigint NOT NULL, "content" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "comments_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "memos" table
CREATE TABLE "public"."memos" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "content" text NOT NULL, "is_public" "public"."memo_state" NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "memos_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "memo_tags" table
CREATE TABLE "public"."memo_tags" ("memo_id" bigint NOT NULL, "tag_id" bigint NOT NULL, PRIMARY KEY ("memo_id", "tag_id"), CONSTRAINT "memo_tags_memo_id_fkey" FOREIGN KEY ("memo_id") REFERENCES "public"."memos" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "memo_tags_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "users_links" table
CREATE TABLE "public"."users_links" ("id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "url" character varying(255) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "users_links_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
